version: '3'
services:
    app:
        container_name: graphql-server
        restart: always
        build: .
        ports: 
            - '8080:3000'
        links: 
           - mongo

    mongo:
        container_name: mongodb
        image: mongo
        volumes: 
           - mongo:/Users/Data/data/db
        ports: 
            - '27017:27017'
            
volumes: 
    mongo: