version: 2
jobs: 
   run_test: 
     docker: 
       - image: circleci/node:12.18.3 
     
     steps: 
        - checkout
        - run: yarn install
        - run: yarn test

workflows: 
    version: 2
    build_test: 
        jobs: 
         - run_test
        
