version: 2
 jobs: # we now have TWO jobs, so that a workflow can coordinate them!
   build: # This is our first job.
     docker: # it uses the docker executor
       - image: circleci/node:12.18.3 
       
     
     steps:
        - run: yarn install
        - run: yarn test


