    name: GitHub Classroom Workflow

    on: [push]

    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        
        
        steps:
           - uses: actions/checkout@v1

           - name: action time
             run: echo '::set-env name=SELECTED::green'
             run: echo 'The selected color is' $SELECTED_COLOR
             with:
                 secret: ${{ secrets.secret }}
         
           
