    name: GitHub Classroom Workflow

    on: [push]

    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
       
        steps:
          - uses: actions/checkout@v2
          - name: create env file
            run: |
                touch .env
                echo "secret='${{secrets.secret}}'" >> .env
          - name: show env file
            run: ls
    
          - uses: education/autograding@v1

           
