    name: GitHub Classroom Workflow

    on: [push]

    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        
        
        steps:
          name: set env
          run: echo '::set-env name=SELECTED::green'
  
          name: Get color
          run: echo 'The selected color is' $SELECTED_COLOR

          with:
            secret: ${{ secrets.secret }}
         
           
