    name: GitHub Classroom Workflow

    on: [push]

    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        env:
          secret: randomsecretfortoken

        steps:
          - name: create env file
            run: |
                touch .env
                echo ENGINE_API_KEY =${{ secrets.secret }} >> .env
          - name: show env file
            run: echo cat .env
          - uses: actions/checkout@v2
          - uses: education/autograding@v1

           
